name: Automated test suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Initialize submodules
      run: |
        git submodule update --init --recursive
    - name: Install poetry
      run: |
        pip install poetry
    - name: Install ganache-cli
      run: |
        npm install -g ganache-cli
    - name: Cook sushi
      run: |
        make copy-abi
    - name: Install dependencies
      run: |
        poetry install
    - name: Run test scripts
      run: |
        poetry run pytest
      env:
        BNB_CHAIN_JSON_RPC: ${{ secrets.BNB_CHAIN_JSON_RPC }}
