name: Automated test suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Initialize submodules
      run: |
        git submodule update --init --recursive
    - name: Cook sushi
      run: |
        make all
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    - name: Run test scripts
      run: |
        poetry run pytest
